# syntax=docker/dockerfile:1
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y && useradd -m docker

RUN apt install -y curl wget build-essential git sudo
RUN apt install -y python3 python3-venv python3-dev python3-pip
RUN apt install -y lsb-release software-properties-common gnupg
RUN apt install -y cmake ninja-build
RUN apt install -y libboost-all-dev

# Install doxygen
RUN sudo apt-get install -y -qq doxygen graphviz

RUN echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER docker

WORKDIR /home/docker

RUN pip install -U jupyter-book sphinx_proof matplotlib numpy

COPY scripts/install_cuda11.0.2.sh /opt/src/scripts/install_cuda11.0.2.sh
COPY scripts/install_llvm15.sh /opt/src/scripts/install_llvm15.sh
COPY scripts/install_rocm.5.4.3.sh /opt/src/scripts/install_rocm.5.4.3.sh

RUN sh /opt/src/scripts/install_llvm15.sh
RUN sh /opt/src/scripts/install_cuda11.0.2.sh
RUN sh /opt/src/scripts/install_rocm.5.4.3.sh

# install level zero
RUN wget https://github.com/oneapi-src/level-zero/releases/download/v1.2.3/level-zero-devel_1.2.3+u18.04_amd64.deb
RUN wget https://github.com/oneapi-src/level-zero/releases/download/v1.2.3/level-zero_1.2.3+u18.04_amd64.deb
RUN sudo dpkg -i ./level-zero*
RUN rm level-zero-devel_1.2.3+u18.04_amd64.deb
RUN rm level-zero_1.2.3+u18.04_amd64.deb

RUN mkdir compilers_gits
RUN mkdir compilers


###################################
## DPC++ (requirement)
###################################
#update cmake
RUN sudo apt-get update
RUN sudo apt-get install -y ca-certificates gpg wget
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN sudo apt-get update
RUN sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
RUN sudo apt-get install -y kitware-archive-keyring
RUN sudo apt-get update
RUN sudo apt-get install -y cmake

#esimd requirement
RUN sudo apt install -y libva-dev libffi-dev libtool

#OpenCL requirement
RUN sudo apt install -y clinfo intel-opencl-icd opencl-headers

#check clinfo
RUN clinfo



###################################
## DPC++
###################################
WORKDIR /home/docker/compilers_gits

RUN git clone https://github.com/intel/llvm -b 2024-WW14

WORKDIR /home/docker/compilers_gits/llvm

# configure dpcpp
RUN CUDA_LIB_PATH=~/opt/cuda/lib64/stubs \
        python3 buildbot/configure.py \
        --llvm-external-projects compiler-rt \
            --cuda \
            --hip \
            --cmake-opt="-DCMAKE_INSTALL_PREFIX=/home/docker/compilers/DPCPP" \
            --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=~/opt/cuda" \
            --cmake-opt="-DSYCL_BUILD_PI_HIP_ROCM_DIR=/opt/rocm"

WORKDIR /home/docker/compilers_gits/llvm/build

RUN ninja all tools/libdevice/libsycldevice
RUN ninja install

WORKDIR /home/docker/compilers_gits
RUN rm -r llvm

###################################
## Opensycl
###################################
WORKDIR /home/docker/compilers_gits

RUN git clone --recurse-submodules https://github.com/AdaptiveCpp/AdaptiveCpp.git

WORKDIR /home/docker/compilers_gits/AdaptiveCpp

RUN cmake -G Ninja \
        -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 \
        -DCLANG_EXECUTABLE_PATH=/usr/bin/clang++-15 \
        -DLLVM_DIR=/usr/lib/llvm-15/cmake \
        -DWITH_CUDA_BACKEND=ON -DWITH_ROCM_BACKEND=ON \
        -DWITH_LEVEL_ZERO_BACKEND=On \
        -DCUDA_TOOLKIT_ROOT_DIR=~/opt/cuda \
        -DROCM_PATH=/opt/rocm \
        -DCMAKE_INSTALL_PREFIX=/home/docker/compilers/AdaptiveCpp_clang15 \
        -B build_clang15

WORKDIR /home/docker/compilers_gits/AdaptiveCpp/build_clang15
RUN ninja install


WORKDIR /home/docker

RUN rm -rf compilers_gits
