name: Linux ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:

  docker_build:
    name: "Docker image gen"
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
